Домашнее задание 1
Discovery19/Tinkoff pull request #1
Opened 2023-10-06 13:20 UTC by Discovery19

Проверка чекстайла, еще не готово

2023-10-08 14:06 UTC, Stasik371 commented
> checkstyle почему-то не работает. Смотреть commit Домашнее_задание

Нужно починить)

2023-10-08 14:07 UTC, Stasik371 commented
А еще советую почитать эту статйеку и придерживаться ей) Хотя бы ААА внедрить)

https://habr.com/ru/articles/507594/

2023-10-08 14:11 UTC, Stasik371 requested changes

2023-10-08 14:11 UTC, Stasik371 commented on src/test/java/edu/hw1/SampleTest.java
> +        int res = Main.countK(1234, 0);
Тут тоже бы комментов докинуть( 

А еще нужны тесткейсы на 1000 и на 4-х значное число с одинаковыми цифрами и 5-значное. Оба должны отдавать -1.

2023-10-08 14:11 UTC, Stasik371 commented on src/test/java/edu/hw1/SampleTest.java
> +        boolean res = Main.knightBoardCapture(new int[][] {{0, 0, 0, 1, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0},
Тут бы тоже докинуть ТК( 
где нет коней и где все кони(

А еще будет круто написать вот так 
<img width="188" alt="image" src="https://github.com/Discovery19/Tinkoff/assets/90406808/334a0318-753c-495d-958e-13022eadb6f3">

чтоб было видно)

2023-10-08 19:41 UTC, Discovery19 commented on README.md
хорошо))) спасибо!

2023-10-08 19:41 UTC, Discovery19 commented on src/main/java/edu/hw1/Main.java
> +    public static boolean isPalindromeDescendant(int a) {
так точно!

2023-10-08 19:45 UTC, Discovery19 commented on src/main/java/edu/hw1/Main.java
> +        int n = a;
если не переприсвоить, будет вылетать ошибка в чекстайле. мне самому это не понравилось...
assignment of parameter n is not allowed (как-то так ошибка звучит)

2023-10-08 19:51 UTC, Discovery19 commented on src/main/java/edu/hw1/Main.java
> +    private static int toBinary(int a) {
private static String toBinary2(int a){
        int n=a;
        StringBuilder sb=new StringBuilder();
        while (n>0){
            sb.append(n%2);
            n/=2;
        }
        return sb.reverse().toString();
   }

2023-10-08 19:52 UTC, Discovery19 commented on src/main/java/edu/hw1/Main.java
> +    private static int toBinary(int a) {
что-то подобное сделать? или дело не в переводе в двоичное, а с листами?

2023-10-10 18:57 UTC, Stasik371 commented on src/main/java/edu/hw1/Main.java
> +        int n = a;
Жесть конечно.. Такое вообще правильно, когда мы работаем со ссылками, но тут примитив... Оставляй)

2023-10-10 19:00 UTC, Stasik371 commented on src/main/java/edu/hw1/Main.java
> +    private static int toBinary(int a) {
Ну что-то типо) Это чтоб не вспоминать информатику за 7 класс)

2023-10-10 19:00 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +            sb.append(string.charAt(i + 1));
Красавчик)

2023-10-10 19:05 UTC, Stasik371 commented on src/test/java/edu/hw1/CountDigitsTest.java
> +    }
```suggestion
    @DisplayName("countDigit стандартный подсчет 4-х значного числа") 
    void countDigitsShouldConvertFour() {
        //arrange
        int fourDigitStandardNumber = 4666
        
        //act
        int res = Task2.countDigits(4666);
        
        //assert
        assertThat(res).isEqualTo(4);
    }
```

2023-10-10 19:05 UTC, Stasik371 commented on src/test/java/edu/hw1/CountDigitsTest.java
> +    }
Нужно внедрить эту практику во **все** тесты(

2023-10-10 19:06 UTC, Stasik371 commented on src/test/java/edu/hw1/CountDigitsTest.java
> +    @DisplayName("2. Количество цифр") void countDigitsShouldConvertOne() {
И не забывай про то, что каждая аннотация с новой строки, это тоже нужно везде

2023-10-11 16:44 UTC, Discovery19 commented on src/test/java/edu/hw1/CountDigitsTest.java
> +    @DisplayName("2. Количество цифр") void countDigitsShouldConvertOne() {
Извините, как-то не замечал. Идея просто сама это делает когда я ctrl+alt+L жму

2023-10-15 17:21 UTC, Stasik371 commented on src/test/java/edu/hw1/CountDigitsTest.java
> +    @Test
До сих пор не вижу(

2023-10-15 17:22 UTC, Stasik371 commented
Привет, допиши, пожалуйста, тесты
<img width="806" alt="image" src="https://github.com/Discovery19/Tinkoff/assets/90406808/3ec10db5-abb6-46cd-bc78-31a1ee6b337d">
 по этому паттерну, без этого не смогу поставить макс. балл(

2023-10-15 19:22 UTC, Discovery19 commented
Извините((

2023-10-16 20:09 UTC, Stasik371 commented
Ничего страшного)

Аппрув!

2023-10-18 21:47 UTC, merged